SELECT EMPNO, ENAME, JOB, HIREDATE, MGR, DEPTNO, DNAME, LOC, SALGRADE, SAL, COMM FROM VIEW_EMP;

SELECT * FROM USER_VIEWS;

SELECT * FROM EMP;


INSERT INTO EMP(EMPNO, ENAME, DEPTNO) VALUES(9999, 'TEST', 30);
COMMIT;


DELETE FROM EMP WHERE EMPNO = 9999;

SELECT E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE, E.SAL, E.COMM, E.DEPTNO, D.DNAME, D.LOC
     , (SELECT S.GRADE
        FROM SALGRADE S
        WHERE E.SAL >= S.LOSAL AND E.SAL <= S.HISAL) SALGRADE
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO
ORDER BY E.EMPNO;
