SELECT USER
FROM DUAL;
--==>>SCOTT

--○ 테이블 생성
CREATE TABLE TBL_MEMBERLIST
( ID    VARCHAR2(30)
, PW    VARCHAR2(20) NOT NULL
, NAME  VARCHAR2(50) NOT NULL
, TEL   VARCHAR2(50) NOT NULL
, EMAIL VARCHAR2(100)
, CONSTRAINT MEMBERLIST_ID_PW PRIMARY KEY(ID)
, CONSTRAINT MEMBERLIST_TEL_UK UNIQUE(TEL)
);


INSERT INTO TBL_MEMBERLIST(ID, PW, NAME, TEL, EMAIL)
VALUES('superman', '1234', '수퍼맨', '010-1111-1111', 'superman@naver.com');

-->한 줄 처리
INSERT INTO TBL_MEMBERLIST(ID, PW, NAME, TEL, EMAIL) VALUES('superman', '1234', '수퍼맨', '010-1111-1111', 'superman@naver.com')
;

SELECT ID, PW, NAME, TEL, EMAIL FROM TBL_MEMBERLIST
;

commit;

DELETE
FROM TBL_MEMBERLIST;


